version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.GH_PASSWORD }}
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    registries:
      - github-octocat
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Europe/Paris"
    allow:
      - dependency-type: "all"
